---
- name: My environment
  hosts: 127.0.0.1
  connection: local
  vars:
    home_directory: "{{ lookup('env', 'HOME') }}"
    user_bin_directory: "{{ lookup('env', 'HOME') }}/bin"

  roles:
    - role: fubarhouse.rust
      vars:
        rust_version: 1.39.0
        cargo_items:
            - name: ripgrep
            - name: fd-find
            - name: bat
            - name: exa
 
  pre_tasks:
    - name: Add fish apt repository
      become: yes
      apt_repository:
          repo: 'ppa:fish-shell/release-3'

    - name: Add golang apt repository
      become: yes
      apt_repository:
          repo: 'ppa:longsleep/golang-backports'

    - name: Install APT packages
      become: yes
      apt:
          name:
            - curl
            - gcc
            - tmux
            - tig
            - fish
            - tldr
            - tree
            - xclip
            - golang-go
            - haskell-platform
            - clang-format
            - clang-tidy
            - clang-tools
            - python3-pip
            - python-pip
            - libx11-dev
            - suckless-tools
            - gawk
            - feh
            - rofi
            - i3lock-fancy
            - libxrandr-dev
            - libxss-dev
            - arandr
            - nodejs
            - nodejs-dev
            - node-gyp
            - libssl1.0-dev
            - npm
            - fonts-firacode
            - clang
            - libclang-6.0-dev
            - libclang-dev
            - llvm
            - llvm-dev
            - llvm-runtime
            - rapidjson-dev

              # polybar dependencies
            - build-essential
            - git
            - cmake
            - cmake-data
            - pkg-config
            - python3-sphinx
            - libcairo2-dev
            - libxcb1-dev
            - libxcb-util0-dev
            - libxcb-randr0-dev
            - libxcb-composite0-dev
            - python-xcbgen
            - xcb-proto
            - libxcb-image0-dev
            - libxcb-ewmh-dev
            - libxcb-icccm4-dev
            - libcurl4

              # polybar optional
            - libxcb-xkb-dev
            - libxcb-xrm-dev 
            - libxcb-cursor-dev
            - libasound2-dev
            - libpulse-dev
            - libjsoncpp-dev
            - libmpdclient-dev
            - libcurl4-openssl-dev 
            - libnl-genl-3-dev

          update_cache: true
          state: present

    - name: Install python 3 packages
      pip:
          executable: '/usr/bin/pip3'
          name:
              - pynvim>=0.3.2
              - ranger-fm>=1.9.2

    - name: Install python 2 packages
      pip:
          executable: '/usr/bin/pip2'
          name:
              - pexpect

    - name: Create home bin directory
      file:
          path: "{{ user_bin_directory }}"
          state: directory

    - name: Download kitty installer
      get_url:
          url: https://sw.kovidgoyal.net/kitty/installer.sh
          dest: "/tmp/kitty_installer.sh"
          mode: '0755'

    - name: Install kitty
      shell: /tmp/kitty_installer.sh

    - name: Create kitty symlink
      file:
        src: "{{ home_directory }}/.local/kitty.app/bin/kitty"
        dest: "{{ user_bin_directory }}/kitty"
        state: link

    - name: Download oh-my-fish installer
      get_url:
          url: https://get.oh-my.fish
          dest: "/tmp/ohmyfish_installer.sh"
          mode: '0755'

    - name: Install oh-my-fish
      expect:
          command: /tmp/ohmyfish_installer.sh
          responses:
              Would you like to remove the existing installation?: y
              Are you sure you want to continue?: y

    - name: Install nodejs packages
      become: yes
      npm:
          name: neovim
          global: yes
          state: present

    - name: Get neovim app
      get_url:
          url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
          dest: "{{ user_bin_directory }}/nvim"
          mode: '0755'

    - name: Update vi alternative
      become: yes
      alternatives:
          name: vi
          link: /usr/bin/vi
          path: "{{ user_bin_directory }}/nvim"

    - name: Create neovim pluggin folder
      file:
          path: "{{ item }}"
          state: directory
      loop:
          - "{{ home_directory }}/.local/share/nvim/site/autoload/"
          - "{{ home_directory }}/.vim/plugged"

    - name: Install vim-plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ home_directory }}/.local/share/nvim/site/autoload/"

    - name: Install tpm
      git:
          repo: https://github.com/tmux-plugins/tpm
          dest: "{{ home_directory }}/.tmux/plugins/tpm"

    - name: Update cabal
      command: cabal update

    - name: Install haskell packages
      command: cabal install {{ item }}
      loop:
          - xmonad
          - xmonad-contrib
          - stack

    - name: Create custom desktop session
      become: yes
      copy:
          src: custom.desktop
          dest: /usr/share/xsessions/custom.desktop
    
